
import { Ticket, Department, UserDetails, TicketStatus, TicketPriority } from '@/models';

// Updated departments with the requested ones
export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Academic Affairs',
    description: 'Handles academic policies, curriculum, and student academic records',
    head: 'Demelyn E. Monzon',
    members: 15,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'Registrar',
    description: 'Manages student enrollment, transcripts, and academic records',
    head: 'Cherrylyn P. Esparagoza',
    members: 8,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'IT',
    description: 'Information Technology support and infrastructure management',
    head: 'Roberto B. Doromal',
    members: 12,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'Finance (Accounting)',
    description: 'Financial management, accounting, and student billing',
    head: 'Berna A. Bulawit',
    members: 10,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'dept-5',
    name: 'Alumni Affairs',
    description: 'Alumni relations and engagement programs',
    head: 'Mr. Robert Alumni',
    members: 5,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'dept-6',
    name: 'Student Affairs (OSAS)',
    description: 'Office of Student Affairs and Services',
    head: 'Alma C. Fernandez',
    members: 20,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'dept-7',
    name: 'Scholarship',
    description: 'Scholarship programs and financial aid assistance',
    head: 'Geronimo A. Cuadra',
    members: 3,
    createdAt: '2024-01-15T08:00:00Z',
  },
];

// Updated users with the new names and added scholarship department
export const mockUsers: UserDetails[] = [
  {
    id: 'user-1',
    name: 'Admin User',
    email: 'admin@pupqc.edu.ph',
    role: 'admin',
    department: 'IT',
    position: 'System Administrator',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Demelyn E. Monzon',
    email: 'demelyn.monzon@pupqc.edu.ph',
    role: 'faculty',
    department: 'Academic Affairs',
    position: 'Department Head',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=demelyn',
    createdAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Cherrylyn P. Esparagoza',
    email: 'cherrylyn.esparagoza@pupqc.edu.ph',
    role: 'faculty',
    department: 'Registrar',
    position: 'Registrar Head',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cherrylyn',
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Roberto B. Doromal',
    email: 'roberto.doromal@pupqc.edu.ph',
    role: 'faculty',
    department: 'IT',
    position: 'IT Director',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=roberto',
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    id: 'user-5',
    name: 'Berna A. Bulawit',
    email: 'berna.bulawit@pupqc.edu.ph',
    role: 'faculty',
    department: 'Finance (Accounting)',
    position: 'Finance Manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=berna',
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'user-6',
    name: 'Mr. Robert Alumni',
    email: 'robert.alumni@pupqc.edu.ph',
    role: 'faculty',
    department: 'Alumni Affairs',
    position: 'Alumni Relations Director',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=robert',
    createdAt: '2024-01-06T00:00:00Z',
  },
  {
    id: 'user-7',
    name: 'Alma C. Fernandez',
    email: 'alma.fernandez@pupqc.edu.ph',
    role: 'faculty',
    department: 'Student Affairs (OSAS)',
    position: 'OSAS Director',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alma',
    createdAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'user-11',
    name: 'Geronimo A. Cuadra',
    email: 'geronimo.cuadra@pupqc.edu.ph',
    role: 'faculty',
    department: 'Scholarship',
    position: 'Scholarship Director',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=geronimo',
    createdAt: '2024-01-11T00:00:00Z',
  },
  {
    id: 'user-8',
    name: 'Juan Dela Cruz',
    email: 'juan.delacruz@pupqc.edu.ph',
    role: 'student',
    department: 'Computer Science',
    studentId: '2024-00001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juan',
    createdAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'user-9',
    name: 'Maria Clara',
    email: 'maria.clara@pupqc.edu.ph',
    role: 'student',
    department: 'Information Technology',
    studentId: '2024-00002',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mariaclara',
    createdAt: '2024-01-09T00:00:00Z',
  },
  {
    id: 'user-10',
    name: 'Jose Rizal Alumni',
    email: 'jose.rizal@gmail.com',
    role: 'alumni',
    department: 'Computer Science',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jose',
    createdAt: '2024-01-10T00:00:00Z',
  },
];

// Sample tickets with updated assignee names
export const mockTickets: Ticket[] = [
  {
    id: 'ticket-1',
    title: 'Unable to access student portal',
    description: 'I am having trouble logging into the student portal. The system shows an error message "Invalid credentials" even though I am using the correct username and password.',
    status: 'open' as TicketStatus,
    priority: 'high' as TicketPriority,
    createdBy: 'user-8',
    creatorName: 'Juan Dela Cruz',
    creatorRole: 'student',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juan',
    department: 'IT',
    createdAt: '2024-12-01T10:30:00Z',
    updatedAt: '2024-12-01T10:30:00Z',
    comments: [],
    attachments: [],
  },
  {
    id: 'ticket-2',
    title: 'Grade discrepancy in Mathematics course',
    description: 'There seems to be an error in my final grade for Mathematics 101. The computed grade does not match my individual scores.',
    status: 'in_progress' as TicketStatus,
    priority: 'medium' as TicketPriority,
    createdBy: 'user-9',
    creatorName: 'Maria Clara',
    creatorRole: 'student',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mariaclara',
    assignedTo: 'user-2',
    assigneeName: 'Demelyn E. Monzon',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=demelyn',
    department: 'Academic Affairs',
    createdAt: '2024-11-28T14:15:00Z',
    updatedAt: '2024-11-29T09:20:00Z',
    comments: [
      {
        id: 'comment-1',
        ticketId: 'ticket-2',
        userId: 'user-2',
        userName: 'Demelyn E. Monzon',
        userRole: 'faculty',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=demelyn',
        content: 'I have reviewed your case and will coordinate with the instructor to verify the grade computation.',
        createdAt: '2024-11-29T09:20:00Z',
        isInternal: false,
      },
    ],
    attachments: [],
  },
  {
    id: 'ticket-3',
    title: 'Request for enrollment certificate',
    description: 'I need an official enrollment certificate for scholarship application. Please provide the document with the official seal.',
    status: 'resolved' as TicketStatus,
    priority: 'low' as TicketPriority,
    createdBy: 'user-8',
    creatorName: 'Juan Dela Cruz',
    creatorRole: 'student',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juan',
    assignedTo: 'user-3',
    assigneeName: 'Cherrylyn P. Esparagoza',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cherrylyn',
    department: 'Registrar',
    createdAt: '2024-11-25T11:00:00Z',
    updatedAt: '2024-11-27T16:30:00Z',
    comments: [
      {
        id: 'comment-2',
        ticketId: 'ticket-3',
        userId: 'user-3',
        userName: 'Cherrylyn P. Esparagoza',
        userRole: 'faculty',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cherrylyn',
        content: 'Your enrollment certificate is ready for pickup at the Registrar office.',
        createdAt: '2024-11-27T16:30:00Z',
        isInternal: false,
      },
    ],
    attachments: [],
  },
  {
    id: 'ticket-4',
    title: 'Tuition fee payment inquiry',
    description: 'I have paid my tuition fees online but the payment is not reflecting in my student account. Please check the payment status.',
    status: 'open' as TicketStatus,
    priority: 'urgent' as TicketPriority,
    createdBy: 'user-9',
    creatorName: 'Maria Clara',
    creatorRole: 'student',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mariaclara',
    department: 'Finance (Accounting)',
    createdAt: '2024-12-02T08:45:00Z',
    updatedAt: '2024-12-02T08:45:00Z',
    comments: [],
    attachments: [],
  },
  {
    id: 'ticket-5',
    title: 'Alumni database update request',
    description: 'I would like to update my contact information in the alumni database. My current address and phone number have changed.',
    status: 'in_progress' as TicketStatus,
    priority: 'low' as TicketPriority,
    createdBy: 'user-10',
    creatorName: 'Jose Rizal Alumni',
    creatorRole: 'alumni',
    creatorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jose',
    assignedTo: 'user-6',
    assigneeName: 'Mr. Robert Alumni',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=robert',
    department: 'Alumni Affairs',
    createdAt: '2024-11-30T13:20:00Z',
    updatedAt: '2024-12-01T10:15:00Z',
    comments: [],
    attachments: [],
  },
];
